apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-gateway-admission-webhook
  labels:
    app: host-gateway-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host-gateway-admission-webhook
  template:
    metadata:
      labels:
        app: host-gateway-admission-webhook
    spec:
      serviceAccount: host-gateway-admission-webhook
      containers:
        - name: host-gateway-admission-webhook
          image: ghcr.io/sj26/host-gateway-admission-webhook
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "443"
            - name: CERT
              value: |
                -----BEGIN CERTIFICATE-----
                MIIFzDCCA7SgAwIBAgIUUMRXiO8SG2aplCIAzc7fg9lab+EwDQYJKoZIhvcNAQEL
                BQAwNTEzMDEGA1UEAwwqaG9zdC1nYXRld2F5LWFkbWlzc2lvbi13ZWJob29rLmRl
                ZmF1bHQuc3ZjMB4XDTI1MDYxMDA5MDk1NFoXDTM1MDYwODA5MDk1NFowNTEzMDEG
                A1UEAwwqaG9zdC1nYXRld2F5LWFkbWlzc2lvbi13ZWJob29rLmRlZmF1bHQuc3Zj
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtV7wyRRBsQ5EC8rMIFlm
                Sx/2TIzI6ey4YxZxgGfIyWtdL0jPAnJjov/qjfeIKfGXVQyg/UooyFsGYT4X6I/R
                CdczemBJDj5jCE5Xm+f6p8qUT5IoY6TMqmvU+1sZRF7RBO4n3zm21b47+d72Jo7M
                d96YJ8htp+L3yT1hw03wt7geMB+6a/NxUD1B7N+e8OzYqQndtj+gfDhMHJq0WZ1c
                tyH9aHUlVGKF1iUMoE/0KCtnu/6nnW8CDGEIABJ3Ot4fIC6Jw3LIojF+6piGnKMT
                LKUogGU0Nx82r9aBZDr9QDlUT4ZYxR0NK0IP6LP/+KSyonKFs693PuamFMghg3X0
                t12ZHz4LKHGJMOucpdp9I4yidbuT6pLNzsr1TXniREOb60XNlj+ukMGS5DESAEzC
                UGsJ60zMbCwZz1x8Dz09s3or97/x/CubIa2aYpbkB/ldCQNbNEs/MPIuk45ULg/Z
                k1bdLRjgGvBgVzDREgrd97TkwwZUh4Hw7AkScHiQAtE3JXB6NRHZteaRnd1RlS7H
                dxBEXxiO8D0Qr/FqohUmyxlNTGmL0oAK9WyNK+tp2NH3D5LBvAEu43jpL3d6Ub5+
                U/nFVsVyKwd5DATwflDh39+Ho7LVO7XLsvxStNetrIROXzUsKil0kG9QkGRPnKmz
                qs0G6hbc7ctdxp90ED7p3L8CAwEAAaOB0zCB0DAdBgNVHQ4EFgQUpBnZzUjOr7tP
                rUUYZKP6C550fWQwHwYDVR0jBBgwFoAUpBnZzUjOr7tPrUUYZKP6C550fWQwDwYD
                VR0TAQH/BAUwAwEB/zB9BgNVHREEdjB0gipob3N0LWdhdGV3YXktYWRtaXNzaW9u
                LXdlYmhvb2suZGVmYXVsdC5zdmOCJmhvc3QtZ2F0ZXdheS1hZG1pc3Npb24td2Vi
                aG9vay5kZWZhdWx0gh5ob3N0LWdhdGV3YXktYWRtaXNzaW9uLXdlYmhvb2swDQYJ
                KoZIhvcNAQELBQADggIBAE5VtJra7XgLQQUFBp/K9Pk3gDf27HW9qL5y2QpYDsqB
                yur424WLx+055Ycfusg9RRAMqLZzqnFKboOuhCilBOoEDuJqoz2UZaW1WUqv3KBk
                hfKSnAQI1pYm+1kmK0K+EwJwEfhAM5sRlmJmLmzEjzcd0MYYFv2kamAjgiai6G8f
                YF1RRfXVJMKtTF9GuEFVxNHhh20kNlCOiEeFO1n5D2Fc5Wh+valZpNSgMm9VsgL8
                9t2wFzR/PcrOJS0jNzSDZjClkNc9TRy7JaAoUd5ZHdrM0GTGuBucLEjJ8xWsfrQA
                G9xhIOnQMmRbSxVUAJ/xgRPINXZcSXJp+rb7/WEsQ71Cw+Ek79sEAe+1GeJ607g7
                X+iw6Rf0JNtbuFxsb58FpmWuPh8ZkCmNDt69tyFes1KrdSvBHUOsHbBlbK6xLrIy
                3GGe7ICX8gYoMf0KODIMYJxVfgxeyfKNBUJpniQfM7wAIENEWYHIQzG8iI132Yl/
                Y60r+xuhG76pArJHeUBrCyzGbMsDr/yB3H9L1PffS7FOHaw2rl6mnd/VOqlKQrni
                kL2B77xRkzUntIwdlbcj6nE8I9azsOda1YQAQl1SHS34ILuG2G6oZnLN7ogIfP6E
                nkWUssfM0aIiD593htTEmAWGbCQAXriEEWNrzr1pLunuiXljfxwNYUIJ3HieIXP/
                -----END CERTIFICATE-----
            - name: KEY
              value: |
                -----BEGIN PRIVATE KEY-----
                MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC1XvDJFEGxDkQL
                yswgWWZLH/ZMjMjp7LhjFnGAZ8jJa10vSM8CcmOi/+qN94gp8ZdVDKD9SijIWwZh
                Phfoj9EJ1zN6YEkOPmMITleb5/qnypRPkihjpMyqa9T7WxlEXtEE7iffObbVvjv5
                3vYmjsx33pgnyG2n4vfJPWHDTfC3uB4wH7pr83FQPUHs357w7NipCd22P6B8OEwc
                mrRZnVy3If1odSVUYoXWJQygT/QoK2e7/qedbwIMYQgAEnc63h8gLonDcsiiMX7q
                mIacoxMspSiAZTQ3Hzav1oFkOv1AOVRPhljFHQ0rQg/os//4pLKicoWzr3c+5qYU
                yCGDdfS3XZkfPgsocYkw65yl2n0jjKJ1u5Pqks3OyvVNeeJEQ5vrRc2WP66QwZLk
                MRIATMJQawnrTMxsLBnPXHwPPT2zeiv3v/H8K5shrZpiluQH+V0JA1s0Sz8w8i6T
                jlQuD9mTVt0tGOAa8GBXMNESCt33tOTDBlSHgfDsCRJweJAC0TclcHo1Edm15pGd
                3VGVLsd3EERfGI7wPRCv8WqiFSbLGU1MaYvSgAr1bI0r62nY0fcPksG8AS7jeOkv
                d3pRvn5T+cVWxXIrB3kMBPB+UOHf34ejstU7tcuy/FK0162shE5fNSwqKXSQb1CQ
                ZE+cqbOqzQbqFtzty13Gn3QQPuncvwIDAQABAoICAASNyTLrSMj2yDuZkG2BgSGC
                wG7knAjPkkOepSPpty9jfDf7NoNjtt+5WDzPScJv1/JhOkuRyJtbObpIUlZbAg8i
                sZ6xezQZ2eez+9wkw3TiD749t7jkwuTGh1b2TxiZ3tqmVibzLoWIXL4l3H1UWYrq
                8lwRWrt75efOHD3In7IlM9DWgxpBxwcSOq0FYlq/P6Ni5Ye1akSkLzkKo1uaqWDJ
                wDCWvGS1gpHBZWNDDqjRii28s52u01jXONmznP3D5PksYfYf1CzKXFrskHivWYRl
                8zHiGKEHrhpVIvOOzZwGtHi4sVLlq1Z6NqcLmfI2xGtyv6umzLIuHV5pNfo0hHvp
                S2NNfTHvY1RrEoZTq0yN6cc2FyjsWQXw6V8LNVnqlXqqVHFh6pXzTncnpcgw6kEI
                DpbWx62ycfH/Ms0AcwXr/svYFZ8gIVe7OvtONzfk4Y3O0obrY8pAOC7joH3QGCRY
                Bjm1A/akFYbTTwy8iwTezxuQh/Agl1PMvS8smVA3HB58dljqwPoknvPcNaMapVz2
                coLVLHFfXmuaGbC0pL8Z7fb19SfWTZ1FMuBViniBXhBeRPflHtS8hUAJ8gz08h5p
                xhdQYvaQ3W8yPeGAUN/P6PdyDOEYIehVUlJ8zjzWzOwDRCLZ/oJDIya6OoJ3dMxM
                tDePNThpk95AOr3yzhF9AoIBAQDnDdG0L9sVBj9IXXwU5v6T5+idjBN74XDkep7z
                0o7obw/EtklPX4OudLilkJ1p+87/shVwIKYYzxAUI4vISGUdX8x9ilme2k35Y/tE
                vbZDLl2as2gSaI1M6G2geCh224Ta/Crv05IviiJRZMBZo3UV8RmYHdg6F7UoGuty
                SEKtYTX2V6zvnfrpXhp5qdjovN5O2tSrWzNGo6lhkNqO6f1plBSrp+DApLv/4XAm
                evl43BzaLm6SxwEW7OiccaK7WavAyTgQMbelfn2u/+A81B/WRnNpEgXFJiv2Wv1r
                pBl2LvRIAlh6m88/03eEGOvOXkWLlb4CX/flJLwd1PdTQhfjAoIBAQDI8+mZpd+q
                4WiXMs+B+B9WfTwpGLfRT7wcki49ML+2R/d1t5agMTOEx3FNmJeYazDcRbocsA4+
                SVslrw9vqi7bA2xi7O5Gq9iD82ww2k2mtenQX1buSPcwNqbGhHEqOr2i6u3l5Dc5
                YcWpYUQkjFtJd2BduOCEEDo2nSTBwEXejWwUpcdcC9RBQDITYOZQFMUfxejBK5Av
                odkhbJhpJvwZMZKcMKzVf6ZHYzrjORMuE+kZ6drV++/c+GDOaxm845IR21uKqJ25
                4Qgzs4Qk8/t/6mZZHTBWZJRx6b6PAcXsKqXwLIX5n2KSmpmORB4ncl7gcB62Ujx7
                /6kF3K189eZ1AoIBAQDitBVxFY+BRnrrFwa7P5bEKsR7aMhpQV7SX1n85Djh6K7x
                FOZDYfVDRDU0Bfvd1HtbOTF9rhsqtmgRSntJjXbg5nEvMIMUsR/WtfoBjZ76tdCU
                DLntbfZOYrPFwn/5dxQZBVlfrRh/WqqncBKnIRGt8L1rGsVg4ogWDKu9mxcJJRuc
                VJRTG4/oUDPr8fHpEf+SIXaPl1FtWwHDwCwiE4ZYhDnv3y1P95Ka02iF6R1EL7yD
                exF1JJt2Egd+EKVZ6/bwlr5SbWXClKTfAyLSrFN8m+17R3qv4O87rjV+2yk8Y3+9
                88c6rgwglO1siEM+XhMgjVE85UrG409MefweDfh/AoIBAHRbp9vsDEMqGiHSrg0X
                2y19fqRdR7LPdKEmk9eirp+htExZbcJ8OtSbl6PSw5TiHHyvc0DBQL4YQ8riPxHt
                fQwcQ1pUzvPk9Y4SGYeAII5zr1uUmQWJAnjMbG1uqwhE0yHO3snLB58WWhnl1EtF
                amZz1TzvnDFcJBkTjQETkGF5iie6hmFqCBFwVo6aAUJFhI8NTeTskKTEFrIf63CX
                vknoRnhiRvGo5GNZtfN0TQLVTJhQrQJSy2Ur/QIJSfHx49arKap0UEAdaV5miBHN
                pMdAttrK5/5eZwY+zrSH1k8VstgLL9iGzdEN6/RQxRUaSI203lO78oHqW7ilO1+s
                EzECggEAEnJyhQPjJjIYqzfCI5ZFHVzfedfwMQ4PUamidn39MUxDo1//1Ig5whxm
                GfEcrOOLWoIn6sZSHkMoDyyYTfLEk73hwolTJGmdkruOw0Hk8F+NbrkZwWrLjpyP
                bhAaGX1BMRXMlxKoMkA+UYwJvkicPHdD7WKyLrTY0zOX/LmQ86nJAiWaqCFMvVXu
                kZ+Uh9tC14p7Auf+jbhUBgu73fzf+XMnXVszqYt5zSXWWMVxvLxVk1jFVexo5xij
                G0n32LpFtS0e+T0D6tAmCirUAFy7dhH0alnnsxVwkWu/oXtl+St9PtiCdSv7DbwQ
                Z2ypsKh7qpIW91kgfayZyM5Iu1m9Pg==
                -----END PRIVATE KEY-----
