apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: host-gateway-admission-webhook
  labels:
    app: host-gateway-admission-webhook
  annotations:
    cert-manager.io/inject-ca-from: host-gateway-admission-webhook-certificate
webhooks:
  - name: host-gateway-admission-webhook.sj26.github.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ6RENDQTdTZ0F3SUJBZ0lVVU1SWGlPOFNHMmFwbENJQXpjN2ZnOWxhYitFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05URXpNREVHQTFVRUF3d3FhRzl6ZEMxbllYUmxkMkY1TFdGa2JXbHpjMmx2YmkxM1pXSm9iMjlyTG1SbApabUYxYkhRdWMzWmpNQjRYRFRJMU1EWXhNREE1TURrMU5Gb1hEVE0xTURZd09EQTVNRGsxTkZvd05URXpNREVHCkExVUVBd3dxYUc5emRDMW5ZWFJsZDJGNUxXRmtiV2x6YzJsdmJpMTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmoKTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF0Vjd3eVJSQnNRNUVDOHJNSUZsbQpTeC8yVEl6STZleTRZeFp4Z0dmSXlXdGRMMGpQQW5Kam92L3FqZmVJS2ZHWFZReWcvVW9veUZzR1lUNFg2SS9SCkNkY3plbUJKRGo1akNFNVhtK2Y2cDhxVVQ1SW9ZNlRNcW12VSsxc1pSRjdSQk80bjN6bTIxYjQ3K2Q3MkpvN00KZDk2WUo4aHRwK0wzeVQxaHcwM3d0N2dlTUIrNmEvTnhVRDFCN04rZThPellxUW5kdGorZ2ZEaE1ISnEwV1oxYwp0eUg5YUhVbFZHS0YxaVVNb0UvMEtDdG51LzZublc4Q0RHRUlBQkozT3Q0ZklDNkp3M0xJb2pGKzZwaUduS01UCkxLVW9nR1UwTng4MnI5YUJaRHI5UURsVVQ0Wll4UjBOSzBJUDZMUC8rS1N5b25LRnM2OTNQdWFtRk1naGczWDAKdDEyWkh6NExLSEdKTU91Y3BkcDlJNHlpZGJ1VDZwTE56c3IxVFhuaVJFT2I2MFhObGordWtNR1M1REVTQUV6QwpVR3NKNjB6TWJDd1p6MXg4RHowOXMzb3I5Ny94L0N1YklhMmFZcGJrQi9sZENRTmJORXMvTVBJdWs0NVVMZy9aCmsxYmRMUmpnR3ZCZ1Z6RFJFZ3JkOTdUa3d3WlVoNEh3N0FrU2NIaVFBdEUzSlhCNk5SSFp0ZWFSbmQxUmxTN0gKZHhCRVh4aU84RDBRci9GcW9oVW15eGxOVEdtTDBvQUs5V3lOSyt0cDJOSDNENUxCdkFFdTQzanBMM2Q2VWI1KwpVL25GVnNWeUt3ZDVEQVR3ZmxEaDM5K0hvN0xWTzdYTHN2eFN0TmV0cklST1h6VXNLaWwwa0c5UWtHUlBuS216CnFzMEc2aGJjN2N0ZHhwOTBFRDdwM0w4Q0F3RUFBYU9CMHpDQjBEQWRCZ05WSFE0RUZnUVVwQm5aelVqT3I3dFAKclVVWVpLUDZDNTUwZldRd0h3WURWUjBqQkJnd0ZvQVVwQm5aelVqT3I3dFByVVVZWktQNkM1NTBmV1F3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pCOUJnTlZIUkVFZGpCMGdpcG9iM04wTFdkaGRHVjNZWGt0WVdSdGFYTnphVzl1CkxYZGxZbWh2YjJzdVpHVm1ZWFZzZEM1emRtT0NKbWh2YzNRdFoyRjBaWGRoZVMxaFpHMXBjM05wYjI0dGQyVmkKYUc5dmF5NWtaV1poZFd4MGdoNW9iM04wTFdkaGRHVjNZWGt0WVdSdGFYTnphVzl1TFhkbFltaHZiMnN3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFFNVZ0SnJhN1hnTFFRVUZCcC9LOVBrM2dEZjI3SFc5cUw1eTJRcFlEc3FCCnl1cjQyNFdMeCswNTVZY2Z1c2c5UlJBTXFMWnpxbkZLYm9PdWhDaWxCT29FRHVKcW96MlVaYVcxV1VxdjNLQmsKaGZLU25BUUkxcFltKzFrbUswSytFd0p3RWZoQU01c1JsbUptTG16RWp6Y2QwTVlZRnYya2FtQWpnaWFpNkc4ZgpZRjFSUmZYVkpNS3RURjlHdUVGVnhOSGhoMjBrTmxDT2lFZUZPMW41RDJGYzVXaCt2YWxacE5TZ01tOVZzZ0w4Cjl0MndGelIvUGNyT0pTMGpOelNEWmpDbGtOYzlUUnk3SmFBb1VkNVpIZHJNMEdUR3VCdWNMRWpKOHhXc2ZyUUEKRzl4aElPblFNbVJiU3hWVUFKL3hnUlBJTlhaY1NYSnArcmI3L1dFc1E3MUN3K0VrNzlzRUFlKzFHZUo2MDdnNwpYK2l3NlJmMEpOdGJ1RnhzYjU4RnBtV3VQaDhaa0NtTkR0Njl0eUZlczFLcmRTdkJIVU9zSGJCbGJLNnhMckl5CjNHR2U3SUNYOGdZb01mMEtPRElNWUp4VmZneGV5ZktOQlVKcG5pUWZNN3dBSUVORVdZSElRekc4aUkxMzJZbC8KWTYwcit4dWhHNzZwQXJKSGVVQnJDeXpHYk1zRHIveUIzSDlMMVBmZlM3Rk9IYXcycmw2bW5kL1ZPcWxLUXJuaQprTDJCNzd4Umt6VW50SXdkbGJjajZuRThJOWF6c09kYTFZUUFRbDFTSFMzNElMdUcyRzZvWm5MTjdvZ0lmUDZFCm5rV1Vzc2ZNMGFJaUQ1OTNodFRFbUFXR2JDUUFYcmlFRVdOcnpyMXBMdW51aVhsamZ4d05ZVUlKM0hpZUlYUC8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: host-gateway-admission-webhook
        namespace: default
        path: "/mutate"
        port: 443
    objectSelector:
      matchExpressions:
        - {
            key: app,
            operator: NotIn,
            values: [host-gateway-admission-webhook],
          }
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
